version: "3.0"

services:
  lusthaft-site:
    image: jekyll/jekyll:latest
    container_name: lusthaft-site
    volumes:
      - .:/srv/jekyll
    ports:
      - 8080:4000
    entrypoint: jekyll serve --verbose #-H localhost
